"""File metadata persistence contracts and implementations."""

from __future__ import annotations

from threading import RLock
from typing import Callable, Protocol
from uuid import uuid4

from google.cloud import firestore
from google.cloud.firestore_v1 import DocumentSnapshot
from google.cloud.firestore_v1.base_query import FieldFilter

from app.files.models import FileMetadata, FileStatus


class FileRepository(Protocol):
    """Owner-scoped storage operations for file metadata."""

    def new_file_id(self) -> str: ...

    def create(self, file: FileMetadata) -> FileMetadata: ...

    def list_for_owner(self, owner_id: str) -> list[FileMetadata]: ...

    def get_for_owner(self, file_id: str, owner_id: str) -> FileMetadata | None: ...

    def delete_for_owner(self, file_id: str, owner_id: str) -> bool: ...


class InMemoryFileRepository:
    """Thread-safe file repository for tests and ephemeral development."""

    def __init__(self) -> None:
        self._files: dict[str, FileMetadata] = {}
        self._lock = RLock()

    def new_file_id(self) -> str:
        return str(uuid4())

    def create(self, file: FileMetadata) -> FileMetadata:
        with self._lock:
            if file.id in self._files:
                raise ValueError("file ID already exists")
            self._files[file.id] = file
            return file

    def list_for_owner(self, owner_id: str) -> list[FileMetadata]:
        with self._lock:
            owned_files = [
                file for file in self._files.values() if file.owner_id == owner_id
            ]
            return sorted(owned_files, key=lambda file: file.created_at, reverse=True)

    def get_for_owner(self, file_id: str, owner_id: str) -> FileMetadata | None:
        with self._lock:
            file = self._files.get(file_id)
            if file is None or file.owner_id != owner_id:
                return None
            return file

    def delete_for_owner(self, file_id: str, owner_id: str) -> bool:
        with self._lock:
            file = self._files.get(file_id)
            if file is None or file.owner_id != owner_id:
                return False
            del self._files[file_id]
            return True


class FirestoreFileRepository:
    """Persist owner-scoped metadata in the top-level files collection."""

    FILES_COLLECTION = "files"

    def __init__(self, client_factory: Callable[[], firestore.Client]) -> None:
        self._client_factory = client_factory

    @property
    def client(self) -> firestore.Client:
        return self._client_factory()

    def new_file_id(self) -> str:
        """Return an auto-ID generated by the Firestore client."""
        return self.client.collection(self.FILES_COLLECTION).document().id

    def create(self, file: FileMetadata) -> FileMetadata:
        self.client.collection(self.FILES_COLLECTION).document(file.id).create(
            self._to_document(file)
        )
        return file

    def list_for_owner(self, owner_id: str) -> list[FileMetadata]:
        query = self.client.collection(self.FILES_COLLECTION).where(
            filter=FieldFilter("owner_id", "==", owner_id)
        )
        files = [self._from_snapshot(snapshot) for snapshot in query.stream()]
        return sorted(
            (file for file in files if file is not None),
            key=lambda file: file.created_at,
            reverse=True,
        )

    def get_for_owner(self, file_id: str, owner_id: str) -> FileMetadata | None:
        snapshot = self.client.collection(self.FILES_COLLECTION).document(file_id).get()
        file = self._from_snapshot(snapshot)
        if file is None or file.owner_id != owner_id:
            return None
        return file

    def delete_for_owner(self, file_id: str, owner_id: str) -> bool:
        client = self.client
        document = client.collection(self.FILES_COLLECTION).document(file_id)
        transaction = client.transaction()

        @firestore.transactional
        def delete_in_transaction(
            active_transaction: firestore.Transaction,
        ) -> bool:
            snapshot = document.get(transaction=active_transaction)
            file = self._from_snapshot(snapshot)
            if file is None or file.owner_id != owner_id:
                return False
            active_transaction.delete(document)
            return True

        return delete_in_transaction(transaction)

    @staticmethod
    def _to_document(file: FileMetadata) -> dict[str, object]:
        return {
            "owner_id": file.owner_id,
            "original_filename": file.original_filename,
            "storage_key": file.storage_key,
            "detected_mime_type": file.detected_mime_type,
            "declared_mime_type": file.declared_mime_type,
            "extension": file.extension,
            "size": file.size,
            "sha256": file.sha256,
            "status": file.status.value,
            "rejection_reason": file.rejection_reason,
            "created_at": file.created_at,
            "updated_at": file.updated_at,
        }

    @staticmethod
    def _from_snapshot(snapshot: DocumentSnapshot | None) -> FileMetadata | None:
        if snapshot is None or not snapshot.exists:
            return None
        data = snapshot.to_dict() or {}
        return FileMetadata(
            id=snapshot.id,
            owner_id=data["owner_id"],
            original_filename=data["original_filename"],
            storage_key=data["storage_key"],
            detected_mime_type=data.get("detected_mime_type"),
            declared_mime_type=data["declared_mime_type"],
            extension=data["extension"],
            size=data["size"],
            sha256=data.get("sha256"),
            status=FileStatus(data["status"]),
            rejection_reason=data.get("rejection_reason"),
            created_at=data["created_at"],
            updated_at=data["updated_at"],
        )
